/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppCompaniesRouteImport } from './routes/_app/companies'
import { Route as AppInvoicingRouteImport } from './routes/_app/invoicing'
import { Route as AppOrderingRouteImport } from './routes/_app/ordering'
import { Route as AppVendorsRouteImport } from './routes/_app/vendors'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicingRoute = AppInvoicingRouteImport.update({
  id: '/invoicing',
  path: '/invoicing',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderingRoute = AppOrderingRouteImport.update({
  id: '/ordering',
  path: '/ordering',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/chat': typeof AppChatRoute
  '/companies': typeof AppCompaniesRoute
  '/invoicing': typeof AppInvoicingRoute
  '/ordering': typeof AppOrderingRoute
  '/vendors': typeof AppVendorsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/chat': typeof AppChatRoute
  '/companies': typeof AppCompaniesRoute
  '/invoicing': typeof AppInvoicingRoute
  '/ordering': typeof AppOrderingRoute
  '/vendors': typeof AppVendorsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/invoicing': typeof AppInvoicingRoute
  '/_app/ordering': typeof AppOrderingRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/chat'
    | '/companies'
    | '/invoicing'
    | '/ordering'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/unauthorized'
    | '/chat'
    | '/companies'
    | '/invoicing'
    | '/ordering'
    | '/vendors'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/unauthorized'
    | '/_app/chat'
    | '/_app/companies'
    | '/_app/invoicing'
    | '/_app/ordering'
    | '/_app/vendors'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoicing': {
      id: '/_app/invoicing'
      path: '/invoicing'
      fullPath: '/invoicing'
      preLoaderRoute: typeof AppInvoicingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordering': {
      id: '/_app/ordering'
      path: '/ordering'
      fullPath: '/ordering'
      preLoaderRoute: typeof AppOrderingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppInvoicingRoute: typeof AppInvoicingRoute
  AppOrderingRoute: typeof AppOrderingRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppInvoicingRoute: AppInvoicingRoute,
  AppOrderingRoute: AppOrderingRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
